package com.sijanstu.recurlytics.components.dashboard.pages;

import com.sijanstu.recurlytics.components.WrapLayout;

/**
 *
 * @author sijanstu
 */
public class DashboardPage extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public DashboardPage() {
        initComponents();
        statsPanel.setLayout(new WrapLayout());
        this.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent evt) {
                statsPanel.revalidate();
                statsPanel.repaint();
            }
        });
        subscribersPanel.setLayout(new WrapLayout());
        this.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent evt) {
                subscribersPanel.revalidate();
                subscribersPanel.repaint();
            }
        });
        subscribersPanel2.setLayout(new WrapLayout());
        this.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent evt) {
                recentScrollpanel1.revalidate();
                recentScrollpanel1.repaint();
            }
        });
        recentScrollpanel1.getVerticalScrollBar().setUnitIncrement(16);
        recentScrollpanel.getVerticalScrollBar().setUnitIncrement(16);
        jScrollPane2.getVerticalScrollBar().setUnitIncrement(16);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        dashboardpanel = new javax.swing.JPanel();
        statsPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        recentScrollpanel = new javax.swing.JScrollPane();
        subscribersPanel = new javax.swing.JPanel();
        subscriberPanel1 = new com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel();
        subscriberPanel2 = new com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel();
        subscriberPanel3 = new com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel();
        subscriberPanel4 = new com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel();
        subscriberPanel5 = new com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel();
        subscriberPanel6 = new com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel();
        subscriberPanel7 = new com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel();
        subscriberPanel8 = new com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel();
        subscriberPanel9 = new com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel();
        subscriberPanel10 = new com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel();
        subscriberPanel11 = new com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel();
        jPanel1 = new javax.swing.JPanel();
        recentScrollpanel1 = new javax.swing.JScrollPane();
        subscribersPanel2 = new javax.swing.JPanel();
        subscriberPanel23 = new com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel();
        subscriberPanel24 = new com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel();
        subscriberPanel25 = new com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel();
        subscriberPanel26 = new com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel();
        subscriberPanel27 = new com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel();
        subscriberPanel28 = new com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel();
        subscriberPanel29 = new com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel();
        subscriberPanel30 = new com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel();
        subscriberPanel31 = new com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel();
        subscriberPanel32 = new com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel();
        subscriberPanel33 = new com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel();
        jPanel2 = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(367, 419));
        setPreferredSize(new java.awt.Dimension(367, 419));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setMinimumSize(new java.awt.Dimension(367, 419));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(387, 419));

        dashboardpanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        dashboardpanel.setMinimumSize(new java.awt.Dimension(387, 419));
        dashboardpanel.setPreferredSize(new java.awt.Dimension(347, 400));

        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Expiring Subscriptions");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("234875");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Active Subscriptions");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 255, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("234875");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Total Subscriptions");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("234875");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Expired Subscriptions");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 51, 51));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("234875");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout statsPanelLayout = new javax.swing.GroupLayout(statsPanel);
        statsPanel.setLayout(statsPanelLayout);
        statsPanelLayout.setHorizontalGroup(
            statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        statsPanelLayout.setVerticalGroup(
            statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsPanelLayout.createSequentialGroup()
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        recentScrollpanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        subscribersPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        subscribersPanel.add(subscriberPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));
        subscribersPanel.add(subscriberPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));
        subscribersPanel.add(subscriberPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        subscribersPanel.add(subscriberPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        subscribersPanel.add(subscriberPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        subscribersPanel.add(subscriberPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        subscribersPanel.add(subscriberPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        subscribersPanel.add(subscriberPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        subscribersPanel.add(subscriberPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        subscribersPanel.add(subscriberPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        subscribersPanel.add(subscriberPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        recentScrollpanel.setViewportView(subscribersPanel);

        jTabbedPane1.addTab("Recent Subscriptions", recentScrollpanel);

        recentScrollpanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        subscribersPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout subscribersPanel2Layout = new javax.swing.GroupLayout(subscribersPanel2);
        subscribersPanel2.setLayout(subscribersPanel2Layout);
        subscribersPanel2Layout.setHorizontalGroup(
            subscribersPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subscribersPanel2Layout.createSequentialGroup()
                .addGroup(subscribersPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subscriberPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subscriberPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(subscribersPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(subscribersPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subscriberPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subscriberPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subscriberPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subscriberPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subscriberPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subscriberPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subscriberPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subscriberPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subscriberPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        subscribersPanel2Layout.setVerticalGroup(
            subscribersPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subscribersPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(subscribersPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subscribersPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(subscriberPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(subscribersPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(subscriberPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(subscribersPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(subscriberPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(subscribersPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(subscriberPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(subscribersPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(subscriberPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(subscribersPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(subscriberPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(subscribersPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(subscriberPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(subscribersPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(subscriberPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(subscribersPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(subscriberPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(subscribersPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(subscriberPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(subscriberPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        recentScrollpanel1.setViewportView(subscribersPanel2);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recentScrollpanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recentScrollpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("All Subscriptions", jPanel1);

        javax.swing.GroupLayout dashboardpanelLayout = new javax.swing.GroupLayout(dashboardpanel);
        dashboardpanel.setLayout(dashboardpanelLayout);
        dashboardpanelLayout.setHorizontalGroup(
            dashboardpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        dashboardpanelLayout.setVerticalGroup(
            dashboardpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardpanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(statsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addGap(5, 5, 5))
        );

        jScrollPane2.setViewportView(dashboardpanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dashboardpanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JScrollPane recentScrollpanel;
    private javax.swing.JScrollPane recentScrollpanel1;
    private javax.swing.JPanel statsPanel;
    private com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel subscriberPanel1;
    private com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel subscriberPanel10;
    private com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel subscriberPanel11;
    private com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel subscriberPanel2;
    private com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel subscriberPanel23;
    private com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel subscriberPanel24;
    private com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel subscriberPanel25;
    private com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel subscriberPanel26;
    private com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel subscriberPanel27;
    private com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel subscriberPanel28;
    private com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel subscriberPanel29;
    private com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel subscriberPanel3;
    private com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel subscriberPanel30;
    private com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel subscriberPanel31;
    private com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel subscriberPanel32;
    private com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel subscriberPanel33;
    private com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel subscriberPanel4;
    private com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel subscriberPanel5;
    private com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel subscriberPanel6;
    private com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel subscriberPanel7;
    private com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel subscriberPanel8;
    private com.sijanstu.recurlytics.components.dashboard.pages.SubscriberPanel subscriberPanel9;
    private javax.swing.JPanel subscribersPanel;
    private javax.swing.JPanel subscribersPanel2;
    // End of variables declaration//GEN-END:variables
}
